# Generated by Django 6.0.3 on 2026-03-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'cash'), ('CART', 'cart')], max_length=10),
        ),
    ]
