# Generated by Django 6.0.3 on 2026-03-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_is_active_customer_order_number_and_more'),
        ('order', '0002_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='customer.customer'),
        ),
    ]
