# Generated by Django 6.0.3 on 2026-03-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SELLER', 'seller'), ('ADMIN', 'admin'), ('MANAGER', 'manager')], max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff_avatar/')),
                ('todays_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
