# Generated by Django 6.0.3 on 2026-03-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productinput'),
        ('shop', '0002_alter_shop_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
